

server:
  port: 10300

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: false
#
#  data:
#    redis:
#      host: localhost
#      port: 6379

